import { type PluginContext } from "@lmstudio/sdk";
import { configSchematics } from "./config";
import { preprocess } from "./promptPreprocessor";

export async function main(context: PluginContext) {
  // Register the configuration schematics generated by your script
  context.withConfigSchematics(configSchematics);

  // Register the preprocessor
  context.withPromptPreprocessor(preprocess);
}
